### PR TITLE
Use iframe for content not managed in this webapp

### PR DESCRIPTION
**Pull request by ghost**
Content not managed by this repository drop navigation header.
Instead, they could be served by an iframe to avoid losing UI elements.

This should be seen as a temporary fix.

@pierre-rouanet can you review the PR?

### CODE REVIEW

**Comment by matthieu-lapeyre** [comment]
can you provide a screenshot of the resulting interface ?

**Comment by ghost** [comment]
@pierre-rouanet this should be good, I'll let you test it again.

**Comment by ghost** [comment]
screen shot 2016-04-26 at 09 39 33

 @matthieu-lapeyre

**Comment by pierre-rouanet** [comment]
Everything is ok for me!

**Pull request merged**
